coverage:
  status:
    project:
      default:
        target: 80%           # Target coverage percentage
        threshold: 5%         # Allow coverage to drop 5% before failing
    patch:
      default:
        target: 70%           # New code should have 70% coverage

  range: 50..100              # Coverage color coding (red at 50%, green at 100%)

comment:
  layout: "header, diff, files"
  behavior: default

ignore:
  - "*/migrations/*"
  - "*/tests/*"
