"""Canonical compound catalog for the allergies app.

Defines every skincare-relevant compound as a CompoundEntry row.
This module is the single source of truth for allergen keys, labels,
INCI names, and subcategory groupings.

Exports:
    COMPOUNDS          — tuple of all CompoundEntry rows
    CompoundEntry       — NamedTuple type for a single compound
    FLAT_ALLERGEN_LABEL_MAP — dict[str, str] mapping allergen_key → display_label
    CATEGORY_CHOICES    — single-entry list for the Allergen.category field
    CATEGORY_CONTACT    — the lone category key ("contact")

Do not import from allergies.constants.choices — this module replaces it.

Reference source:
    INCI names and CAS numbers are verified against the EU CosIng
    (Cosmetic Ingredient) database maintained by the European Commission:
    https://ec.europa.eu/growth/tools-databases/cosing/

    INCIDecoder (incidecoder.com) is used as a secondary cross-reference
    to confirm which INCI names appear on real product labels.

    When CosIng lists multiple CAS numbers for a single INCI name, the
    primary CAS (first listed in CosIng) is used unless a more specific
    one applies to the cosmetic use case.

    When a single allergen concern spans multiple INCI-distinct species
    or derivatives (e.g. Cymbopogon Citratus vs Flexuosus vs Schoenanthus
    for lemongrass, or Hydrolyzed Soy Protein vs Glycine Soja Extract for
    soy), this catalog keeps one CompoundEntry per chemically distinct
    substance. Variant names are stored in common_names for future alias
    resolution. User-facing allergen grouping ("I'm allergic to soy") is
    resolved by the AllergenAlias layer, not by merging entries here.
    See STATUS.md § Compound Catalog Design Decisions for full rationale.
"""

from typing import Final, NamedTuple

# ============================================================================
# Category constants — single-category catalog
# ============================================================================

CATEGORY_CONTACT: Final[str] = "contact"

CATEGORY_CHOICES: Final[list[tuple[str, str]]] = [
    (CATEGORY_CONTACT, "Contact/Topical Allergens"),
]


# ============================================================================
# CompoundEntry definition
# ============================================================================


class CompoundEntry(NamedTuple):
    """A single compound in the allergen catalog.

    Fields:
        key:            Canonical allergen_key stored in the DB.
                        Lowercase, underscored, no special characters.
        inci_name:      International Nomenclature of Cosmetic Ingredients name.
                        Empty string if no standard INCI name exists.
        display_label:  Human-readable label shown in the UI.
        category:       Always "contact" in the current catalog.
        subcategory:    Grouping for checkbox display (e.g. "Fragrances").
        common_names:   Tuple of alternate names for future synonym mapping.
        cas_number:     CAS Registry Number. Empty string if unknown.
        eu_annex_iii:   True if listed in EU Cosmetics Regulation Annex III.
        regulatory_ref: Regulation reference string. Empty if none.
    """

    key: str
    inci_name: str
    display_label: str
    category: str
    subcategory: str
    common_names: tuple[str, ...]
    cas_number: str
    eu_annex_iii: bool
    regulatory_ref: str


# ============================================================================
# Compound data — organized by subcategory
# ============================================================================

_ACIDS_AND_EXFOLIANTS: Final[tuple[CompoundEntry, ...]] = (
    CompoundEntry(
        key="glycolic_acid",
        inci_name="Glycolic Acid",
        display_label="Glycolic Acid",
        category=CATEGORY_CONTACT,
        subcategory="Acids & Exfoliants",
        common_names=("glycolic acid", "hydroxyacetic acid"),
        cas_number="79-14-1",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="salicylic_acid",
        inci_name="Salicylic Acid",
        display_label="Salicylic Acid",
        category=CATEGORY_CONTACT,
        subcategory="Acids & Exfoliants",
        common_names=("salicylic acid", "BHA", "beta hydroxy acid"),
        cas_number="69-72-7",
        eu_annex_iii=True,
        regulatory_ref="EU Annex III/98",
    ),
    CompoundEntry(
        key="lactic_acid",
        inci_name="Lactic Acid",
        display_label="Lactic Acid",
        category=CATEGORY_CONTACT,
        subcategory="Acids & Exfoliants",
        common_names=("lactic acid", "AHA"),
        cas_number="50-21-5",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="citric_acid",
        inci_name="Citric Acid",
        display_label="Citric Acid",
        category=CATEGORY_CONTACT,
        subcategory="Acids & Exfoliants",
        common_names=("citric acid",),
        cas_number="77-92-9",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="benzoic_acid",
        inci_name="Benzoic Acid",
        display_label="Benzoic Acid",
        category=CATEGORY_CONTACT,
        subcategory="Acids & Exfoliants",
        common_names=("benzoic acid",),
        cas_number="65-85-0",
        eu_annex_iii=True,
        regulatory_ref="EU Annex III/1",
    ),
    CompoundEntry(
        key="sorbic_acid",
        inci_name="Sorbic Acid",
        display_label="Sorbic Acid",
        category=CATEGORY_CONTACT,
        subcategory="Acids & Exfoliants",
        common_names=("sorbic acid",),
        cas_number="110-44-1",
        eu_annex_iii=True,
        regulatory_ref="EU Annex III/7",
    ),
)

_BOTANICALS_AND_ESSENTIAL_OILS: Final[tuple[CompoundEntry, ...]] = (
    CompoundEntry(
        key="tea_tree_oil",
        inci_name="Melaleuca Alternifolia Leaf Oil",
        display_label="Tea Tree Oil",
        category=CATEGORY_CONTACT,
        subcategory="Botanicals & Essential Oils",
        common_names=("tea tree oil", "melaleuca oil"),
        cas_number="68647-73-4",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="lavender_oil",
        inci_name="Lavandula Angustifolia Oil",
        display_label="Lavender Oil",
        category=CATEGORY_CONTACT,
        subcategory="Botanicals & Essential Oils",
        common_names=("lavender oil", "lavandula oil"),
        cas_number="8000-28-0",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="peppermint_oil",
        inci_name="Mentha Piperita Oil",
        display_label="Peppermint Oil",
        category=CATEGORY_CONTACT,
        subcategory="Botanicals & Essential Oils",
        common_names=("peppermint oil",),
        cas_number="8006-90-4",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="eucalyptus_oil",
        inci_name="Eucalyptus Globulus Leaf Oil",
        display_label="Eucalyptus Oil",
        category=CATEGORY_CONTACT,
        subcategory="Botanicals & Essential Oils",
        common_names=("eucalyptus oil",),
        cas_number="8000-48-4",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="rose_oil",
        inci_name="Rosa Damascena Flower Oil",
        display_label="Rose Oil",
        category=CATEGORY_CONTACT,
        subcategory="Botanicals & Essential Oils",
        common_names=("rose oil", "rose otto", "attar of roses"),
        cas_number="8007-01-0",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="chamomile",
        inci_name="Chamomilla Recutita Extract",
        display_label="Chamomile",
        category=CATEGORY_CONTACT,
        subcategory="Botanicals & Essential Oils",
        common_names=("chamomile", "matricaria"),
        cas_number="8002-66-2",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="ylang_ylang",
        inci_name="Cananga Odorata Flower Oil",
        display_label="Ylang Ylang",
        category=CATEGORY_CONTACT,
        subcategory="Botanicals & Essential Oils",
        common_names=("ylang ylang", "cananga oil"),
        cas_number="8006-81-3",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="sandalwood",
        inci_name="Santalum Album Oil",
        display_label="Sandalwood",
        category=CATEGORY_CONTACT,
        subcategory="Botanicals & Essential Oils",
        common_names=("sandalwood", "sandalwood oil"),
        cas_number="8006-87-9",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="bergamot_oil",
        inci_name="Citrus Aurantium Bergamia Fruit Oil",
        display_label="Bergamot Oil",
        category=CATEGORY_CONTACT,
        subcategory="Botanicals & Essential Oils",
        common_names=("bergamot oil",),
        cas_number="8007-75-8",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="lemongrass_oil",
        inci_name="Cymbopogon Citratus Leaf Oil",
        display_label="Lemongrass Oil",
        category=CATEGORY_CONTACT,
        subcategory="Botanicals & Essential Oils",
        common_names=(
            "lemongrass oil",
            "Cymbopogon Flexuosus Oil",
            "Cymbopogon Schoenanthus Oil",
        ),
        cas_number="8007-02-1",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
)

_COLORANTS_AND_DYES: Final[tuple[CompoundEntry, ...]] = (
    CompoundEntry(
        key="ci_dyes",
        inci_name="CI (Various)",
        display_label="CI Dyes (Color Index)",
        category=CATEGORY_CONTACT,
        subcategory="Colorants & Dyes",
        common_names=("CI dyes", "color index dyes"),
        cas_number="",
        eu_annex_iii=False,
        regulatory_ref="EU Annex IV (colorants)",
    ),
    CompoundEntry(
        key="fd_c_dyes",
        inci_name="FD&C (Various)",
        display_label="FD&C Dyes",
        category=CATEGORY_CONTACT,
        subcategory="Colorants & Dyes",
        common_names=("FD&C dyes", "FDA certified dyes"),
        cas_number="",
        eu_annex_iii=False,
        regulatory_ref="FDA 21 CFR 74",
    ),
    CompoundEntry(
        key="carmine",
        inci_name="CI 75470",
        display_label="Carmine (CI 75470)",
        category=CATEGORY_CONTACT,
        subcategory="Colorants & Dyes",
        common_names=("carmine", "cochineal", "natural red 4"),
        cas_number="1390-65-4",
        eu_annex_iii=False,
        regulatory_ref="EU Annex IV",
    ),
    CompoundEntry(
        key="iron_oxides",
        inci_name="Iron Oxides",
        display_label="Iron Oxides",
        category=CATEGORY_CONTACT,
        subcategory="Colorants & Dyes",
        common_names=("iron oxides", "CI 77491", "CI 77492", "CI 77499"),
        cas_number="",
        eu_annex_iii=False,
        regulatory_ref="EU Annex IV",
    ),
    CompoundEntry(
        key="mica",
        inci_name="Mica",
        display_label="Mica",
        category=CATEGORY_CONTACT,
        subcategory="Colorants & Dyes",
        common_names=("mica", "CI 77019"),
        cas_number="12001-26-2",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
)

_GENERAL_CONTACT_ALLERGENS: Final[tuple[CompoundEntry, ...]] = (
    CompoundEntry(
        key="nickel",
        inci_name="Nickel",
        display_label="Nickel",
        category=CATEGORY_CONTACT,
        subcategory="General Contact Allergens",
        common_names=("nickel", "nickel sulfate"),
        cas_number="7440-02-0",
        eu_annex_iii=False,
        regulatory_ref="EU REACH Annex XVII/27",
    ),
    CompoundEntry(
        key="latex",
        inci_name="Hevea Brasiliensis",
        display_label="Latex",
        category=CATEGORY_CONTACT,
        subcategory="General Contact Allergens",
        common_names=("latex", "natural rubber latex"),
        cas_number="9006-04-6",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="lanolin",
        inci_name="Lanolin",
        display_label="Lanolin",
        category=CATEGORY_CONTACT,
        subcategory="General Contact Allergens",
        common_names=("lanolin", "wool wax", "wool grease", "adeps lanae"),
        cas_number="8006-54-0",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
)

# --- Fragrances: EU 26 + 2023 expansion (EU 2023/1545) ---
_FRAGRANCES: Final[tuple[CompoundEntry, ...]] = (
    # --- Original 26 (pre-2023 Annex III) ---
    CompoundEntry(
        key="amyl_cinnamal",
        inci_name="Amyl Cinnamal",
        display_label="Amyl Cinnamal",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("amyl cinnamal", "alpha-amyl cinnamaldehyde"),
        cas_number="122-40-7",
        eu_annex_iii=True,
        regulatory_ref="EU Annex III/67",
    ),
    CompoundEntry(
        key="amylcinnamyl_alcohol",
        inci_name="Amylcinnamyl Alcohol",
        display_label="Amylcinnamyl Alcohol",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("amylcinnamyl alcohol",),
        cas_number="101-85-9",
        eu_annex_iii=True,
        regulatory_ref="EU Annex III/68",
    ),
    CompoundEntry(
        key="anise_alcohol",
        inci_name="Anise Alcohol",
        display_label="Anise Alcohol",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("anise alcohol", "anisyl alcohol"),
        cas_number="105-13-5",
        eu_annex_iii=True,
        regulatory_ref="EU Annex III/69",
    ),
    CompoundEntry(
        key="benzyl_alcohol",
        inci_name="Benzyl Alcohol",
        display_label="Benzyl Alcohol",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("benzyl alcohol",),
        cas_number="100-51-6",
        eu_annex_iii=True,
        regulatory_ref="EU Annex III/34",
    ),
    CompoundEntry(
        key="benzyl_benzoate",
        inci_name="Benzyl Benzoate",
        display_label="Benzyl Benzoate",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("benzyl benzoate",),
        cas_number="120-51-4",
        eu_annex_iii=True,
        regulatory_ref="EU Annex III/70",
    ),
    CompoundEntry(
        key="benzyl_cinnamate",
        inci_name="Benzyl Cinnamate",
        display_label="Benzyl Cinnamate",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("benzyl cinnamate",),
        cas_number="103-41-3",
        eu_annex_iii=True,
        regulatory_ref="EU Annex III/71",
    ),
    CompoundEntry(
        key="benzyl_salicylate",
        inci_name="Benzyl Salicylate",
        display_label="Benzyl Salicylate",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("benzyl salicylate",),
        cas_number="118-58-1",
        eu_annex_iii=True,
        regulatory_ref="EU Annex III/72",
    ),
    CompoundEntry(
        key="cinnamyl_alcohol",
        inci_name="Cinnamyl Alcohol",
        display_label="Cinnamyl Alcohol",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("cinnamyl alcohol", "cinnamic alcohol"),
        cas_number="104-54-1",
        eu_annex_iii=True,
        regulatory_ref="EU Annex III/73",
    ),
    CompoundEntry(
        key="cinnamal",
        inci_name="Cinnamal",
        display_label="Cinnamal",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("cinnamal", "cinnamaldehyde", "cinnamic aldehyde"),
        cas_number="104-55-2",
        eu_annex_iii=True,
        regulatory_ref="EU Annex III/74",
    ),
    CompoundEntry(
        key="citral",
        inci_name="Citral",
        display_label="Citral",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("citral", "geranial", "neral"),
        cas_number="5392-40-5",
        eu_annex_iii=True,
        regulatory_ref="EU Annex III/75",
    ),
    CompoundEntry(
        key="citronellol",
        inci_name="Citronellol",
        display_label="Citronellol",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("citronellol",),
        cas_number="106-22-9",
        eu_annex_iii=True,
        regulatory_ref="EU Annex III/76",
    ),
    CompoundEntry(
        key="coumarin",
        inci_name="Coumarin",
        display_label="Coumarin",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("coumarin",),
        cas_number="91-64-5",
        eu_annex_iii=True,
        regulatory_ref="EU Annex III/77",
    ),
    CompoundEntry(
        key="eugenol",
        inci_name="Eugenol",
        display_label="Eugenol",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("eugenol",),
        cas_number="97-53-0",
        eu_annex_iii=True,
        regulatory_ref="EU Annex III/78",
    ),
    CompoundEntry(
        key="farnesol",
        inci_name="Farnesol",
        display_label="Farnesol",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("farnesol",),
        cas_number="4602-84-0",
        eu_annex_iii=True,
        regulatory_ref="EU Annex III/79",
    ),
    CompoundEntry(
        key="geraniol",
        inci_name="Geraniol",
        display_label="Geraniol",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("geraniol",),
        cas_number="106-24-1",
        eu_annex_iii=True,
        regulatory_ref="EU Annex III/80",
    ),
    CompoundEntry(
        key="hexyl_cinnamal",
        inci_name="Hexyl Cinnamal",
        display_label="Hexyl Cinnamal",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("hexyl cinnamal", "hexyl cinnamic aldehyde"),
        cas_number="101-86-0",
        eu_annex_iii=True,
        regulatory_ref="EU Annex III/81",
    ),
    CompoundEntry(
        key="hydroxycitronellal",
        inci_name="Hydroxycitronellal",
        display_label="Hydroxycitronellal",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("hydroxycitronellal",),
        cas_number="107-75-5",
        eu_annex_iii=True,
        regulatory_ref="EU Annex III/82",
    ),
    CompoundEntry(
        key="hydroxyisohexyl_3_cyclohexene_carboxaldehyde",  # gitleaks:allow
        inci_name="Hydroxyisohexyl 3-Cyclohexene Carboxaldehyde",
        display_label="Hydroxyisohexyl 3-Cyclohexene Carboxaldehyde (HICC / Lyral)",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("HICC", "lyral"),
        cas_number="31906-04-4",
        eu_annex_iii=True,
        regulatory_ref="EU Annex III/83 (banned 2021)",
    ),
    CompoundEntry(
        key="isoeugenol",
        inci_name="Isoeugenol",
        display_label="Isoeugenol",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("isoeugenol",),
        cas_number="97-54-1",
        eu_annex_iii=True,
        regulatory_ref="EU Annex III/84",
    ),
    CompoundEntry(
        key="lilial",
        inci_name="Butylphenyl Methylpropional",
        display_label="Lilial (Butylphenyl Methylpropional)",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("lilial", "butylphenyl methylpropional"),
        cas_number="80-54-6",
        eu_annex_iii=True,
        regulatory_ref="EU Annex II/1666 (banned 2022)",
    ),
    CompoundEntry(
        key="limonene",
        inci_name="Limonene",
        display_label="Limonene",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("limonene", "d-limonene"),
        cas_number="5989-27-5",
        eu_annex_iii=True,
        regulatory_ref="EU Annex III/88",
    ),
    CompoundEntry(
        key="linalool",
        inci_name="Linalool",
        display_label="Linalool",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("linalool",),
        cas_number="78-70-6",
        eu_annex_iii=True,
        regulatory_ref="EU Annex III/89",
    ),
    CompoundEntry(
        key="methyl_2_octynoate",
        inci_name="Methyl 2-Octynoate",
        display_label="Methyl 2-Octynoate",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("methyl 2-octynoate", "methyl heptine carbonate"),
        cas_number="111-12-6",
        eu_annex_iii=True,
        regulatory_ref="EU Annex III/90",
    ),
    CompoundEntry(
        key="alpha_isomethyl_ionone",
        inci_name="Alpha-Isomethyl Ionone",
        display_label="Alpha-Isomethyl Ionone",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("alpha-isomethyl ionone",),
        cas_number="127-51-5",
        eu_annex_iii=True,
        regulatory_ref="EU Annex III/91",
    ),
    CompoundEntry(
        key="evernia_prunastri",
        inci_name="Evernia Prunastri Extract",
        display_label="Evernia Prunastri (Oakmoss Extract)",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("oakmoss", "evernia prunastri"),
        cas_number="90028-68-5",
        eu_annex_iii=True,
        regulatory_ref="EU Annex III/92",
    ),
    CompoundEntry(
        key="evernia_furfuracea",
        inci_name="Evernia Furfuracea Extract",
        display_label="Evernia Furfuracea (Treemoss Extract)",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("treemoss", "evernia furfuracea"),
        cas_number="90028-67-4",
        eu_annex_iii=True,
        regulatory_ref="EU Annex III/93",
    ),
    # --- 2023 Expansion (EU 2023/1545 additions) ---
    CompoundEntry(
        key="acetyl_cedrene",
        inci_name="Acetyl Cedrene",
        display_label="Acetyl Cedrene",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("acetyl cedrene",),
        cas_number="32388-55-9",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="beta_damascenone",
        inci_name="Beta-Damascenone",
        display_label="Beta-Damascenone",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("beta-damascenone", "damascenone"),
        cas_number="23726-93-4",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="butyl_acetate",
        inci_name="Butyl Acetate",
        display_label="Butyl Acetate",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("butyl acetate",),
        cas_number="123-86-4",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="camphene",
        inci_name="Camphene",
        display_label="Camphene",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("camphene",),
        cas_number="79-92-5",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="camphor",
        inci_name="Camphor",
        display_label="Camphor",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("camphor",),
        cas_number="76-22-2",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="carvone",
        inci_name="Carvone",
        display_label="Carvone",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("carvone", "d-carvone", "l-carvone"),
        cas_number="6485-40-1",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="cedrol",
        inci_name="Cedrol",
        display_label="Cedrol",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("cedrol", "cedar camphor"),
        cas_number="77-53-2",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="citronellal",
        inci_name="Citronellal",
        display_label="Citronellal",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("citronellal",),
        cas_number="106-23-0",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="cyclamen_aldehyde",
        inci_name="Cyclamen Aldehyde",
        display_label="Cyclamen Aldehyde",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("cyclamen aldehyde",),
        cas_number="103-95-7",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="decyl_aldehyde",
        inci_name="Decanal",
        display_label="Decyl Aldehyde",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("decyl aldehyde", "decanal", "capric aldehyde"),
        cas_number="112-31-2",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="dihydrocoumarin",
        inci_name="Dihydrocoumarin",
        display_label="Dihydrocoumarin",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("dihydrocoumarin",),
        cas_number="119-84-6",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="dimethyl_benzyl_carbinyl_acetate",
        inci_name="Dimethyl Benzyl Carbinyl Acetate",
        display_label="Dimethyl Benzyl Carbinyl Acetate",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("DMBCA",),
        cas_number="151-05-3",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="ethylene_brassylate",
        inci_name="Ethylene Brassylate",
        display_label="Ethylene Brassylate",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("ethylene brassylate", "musk T"),
        cas_number="105-95-3",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="hexadecanolactone",
        inci_name="Hexadecanolactone",
        display_label="Hexadecanolactone",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("hexadecanolactone",),
        cas_number="109-29-5",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="hexyl_salicylate",
        inci_name="Hexyl Salicylate",
        display_label="Hexyl Salicylate",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("hexyl salicylate",),
        cas_number="6259-76-3",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="ionone",
        inci_name="Ionone",
        display_label="Ionone (Alpha and Beta)",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("ionone", "alpha-ionone", "beta-ionone"),
        cas_number="14901-07-6",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="isocyclemone_e",
        inci_name="Isocyclemone E",
        display_label="Isocyclemone E",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("isocyclemone E",),
        cas_number="37609-25-9",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="lyratyl_acetate",
        inci_name="Lyratyl Acetate",
        display_label="Lyratyl Acetate",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("lyratyl acetate",),
        cas_number="",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="menthol",
        inci_name="Menthol",
        display_label="Menthol",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("menthol", "l-menthol"),
        cas_number="89-78-1",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="methyl_ionone",
        inci_name="Methyl Ionone",
        display_label="Methyl Ionone",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("methyl ionone",),
        cas_number="1335-46-2",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="musk_ambrette",
        inci_name="Musk Ambrette",
        display_label="Musk Ambrette",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("musk ambrette",),
        cas_number="83-66-9",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="musk_tibetene",
        inci_name="Musk Tibetene",
        display_label="Musk Tibetene",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("musk tibetene",),
        cas_number="145-39-1",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="nonadienal",
        inci_name="2,4-Nonadienal",
        display_label="2,4-Nonadienal",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("nonadienal", "2,4-nonadienal"),
        cas_number="5910-87-2",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="nonyl_aldehyde",
        inci_name="Nonanal",
        display_label="Nonyl Aldehyde",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("nonyl aldehyde", "nonanal", "pelargonaldehyde"),
        cas_number="124-19-6",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="pentadecalactone",
        inci_name="Pentadecalactone",
        display_label="Pentadecalactone",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("pentadecalactone", "exaltolide"),
        cas_number="106-02-5",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="phenylacetaldehyde",
        inci_name="Phenylacetaldehyde",
        display_label="Phenylacetaldehyde",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("phenylacetaldehyde",),
        cas_number="122-78-1",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="phenoxyethanol_fragrance",
        inci_name="Phenoxyethanol",
        display_label="Phenoxyethanol (Fragrance Use)",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("phenoxyethanol",),
        cas_number="122-99-6",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="rose_ketone_4",
        inci_name="Rose Ketone-4",
        display_label="Rose Ketone-4 (Delta-Damascone)",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("rose ketone-4", "delta-damascone"),
        cas_number="23696-85-7",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="santalol",
        inci_name="Santalol",
        display_label="Santalol (Alpha and Beta)",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("santalol", "alpha-santalol", "beta-santalol"),
        cas_number="11031-45-1",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="terpineol",
        inci_name="Terpineol",
        display_label="Terpineol",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("terpineol", "alpha-terpineol"),
        cas_number="98-55-5",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="tetramethyl_acetyloctahydronaphthalenes",
        inci_name="Tetramethyl Acetyloctahydronaphthalenes",
        display_label="Tetramethyl Acetyloctahydronaphthalenes (OTNE)",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("OTNE", "iso E super analogue", "iso E super", "vertofix coeur"),
        cas_number="54464-57-2",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="trimethylbenzenepropanol",
        inci_name="Trimethylbenzenepropanol",
        display_label="Trimethylbenzenepropanol (Majantol)",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("majantol", "trimethylbenzenepropanol"),
        cas_number="103694-68-4",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="pinus_mugo",
        inci_name="Pinus Mugo Twig/Leaf Oil",
        display_label="Pinus Mugo",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("pinus mugo", "dwarf pine oil", "mountain pine oil"),
        cas_number="90082-72-7",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="pinus_pumila",
        inci_name="Pinus Pumila Twig/Leaf Oil",
        display_label="Pinus Pumila",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("pinus pumila", "dwarf siberian pine oil"),
        cas_number="97676-05-6",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="cedrus_atlantica",
        inci_name="Cedrus Atlantica Bark Oil",
        display_label="Cedrus Atlantica (Atlas Cedarwood)",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("cedrus atlantica", "atlas cedarwood oil", "cedarwood atlas"),
        cas_number="92201-55-3",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="turpentine",
        inci_name="Pinus Palustris Oil",
        display_label="Turpentine",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("turpentine", "oil of turpentine", "spirit of turpentine"),
        cas_number="8006-64-2",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="alpha_terpinene",
        inci_name="Alpha-Terpinene",
        display_label="Alpha-Terpinene",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("alpha-terpinene",),
        cas_number="99-86-5",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="terpinolene",
        inci_name="Terpinolene",
        display_label="Terpinolene",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("terpinolene", "delta-terpinene"),
        cas_number="586-62-9",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="myroxylon_pereirae",
        inci_name="Myroxylon Pereirae Resin",
        display_label="Myroxylon Pereirae (Balsam of Peru)",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("balsam of peru", "myroxylon pereirae", "peru balsam"),
        cas_number="8007-00-9",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="rose_ketones",
        inci_name="Rose Ketones",
        display_label="Rose Ketones",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("rose ketones", "damascenone", "damascone"),
        cas_number="",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="propylidenephthalide",
        inci_name="3-Propylidenephthalide",
        display_label="3-Propylidenephthalide",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("3-propylidenephthalide", "propylidenephthalide"),
        cas_number="17369-59-4",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="lippia_citriodora",
        inci_name="Lippia Citriodora Leaf/Stem Extract",
        display_label="Lippia Citriodora (Lemon Verbena)",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("lippia citriodora", "lemon verbena", "verbena absolute"),
        cas_number="8024-12-2",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="methyl_salicylate",
        inci_name="Methyl Salicylate",
        display_label="Methyl Salicylate",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("methyl salicylate", "oil of wintergreen"),
        cas_number="119-36-8",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="amyl_salicylate",
        inci_name="Amyl Salicylate",
        display_label="Amyl Salicylate",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("amyl salicylate", "pentyl salicylate"),
        cas_number="2050-08-0",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="anethole",
        inci_name="Anethole",
        display_label="Anethole",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("anethole", "trans-anethole", "anise camphor"),
        cas_number="4180-23-8",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="benzaldehyde",
        inci_name="Benzaldehyde",
        display_label="Benzaldehyde",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("benzaldehyde", "benzoic aldehyde", "almond oil artificial"),
        cas_number="100-52-7",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="beta_caryophyllene",
        inci_name="Beta-Caryophyllene",
        display_label="Beta-Caryophyllene",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("beta-caryophyllene", "caryophyllene"),
        cas_number="87-44-5",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="dimethyl_phenethyl_acetate",
        inci_name="Dimethyl Phenethyl Acetate",
        display_label="Dimethyl Phenethyl Acetate",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("dimethyl phenethyl acetate", "DMPEA"),
        cas_number="10094-34-5",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="hexamethylindanopyran",
        inci_name="Hexamethylindanopyran",
        display_label="Hexamethylindanopyran (Galaxolide)",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("hexamethylindanopyran", "galaxolide", "HHCB"),
        cas_number="1222-05-5",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="linalyl_acetate",
        inci_name="Linalyl Acetate",
        display_label="Linalyl Acetate",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("linalyl acetate", "linalool acetate"),
        cas_number="115-95-7",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="trimethylcyclopentenyl_methylisopentenol",
        inci_name="Trimethylcyclopentenyl Methylisopentenol",
        display_label="Trimethylcyclopentenyl Methylisopentenol",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("trimethylcyclopentenyl methylisopentenol",),
        cas_number="68705-52-2",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="salicylaldehyde",
        inci_name="Salicylaldehyde",
        display_label="Salicylaldehyde",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("salicylaldehyde", "2-hydroxybenzaldehyde"),
        cas_number="90-02-8",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
    CompoundEntry(
        key="sclareol",
        inci_name="Sclareol",
        display_label="Sclareol",
        category=CATEGORY_CONTACT,
        subcategory="Fragrances",
        common_names=("sclareol", "clary sage sclareol"),
        cas_number="515-03-7",
        eu_annex_iii=True,
        regulatory_ref="EU 2023/1545",
    ),
)

# --- Preservatives (decomposed from group keys) ---
_PRESERVATIVES: Final[tuple[CompoundEntry, ...]] = (
    # Parabens decomposed: parabens → methylparaben, propylparaben, butylparaben, ethylparaben
    CompoundEntry(
        key="methylparaben",
        inci_name="Methylparaben",
        display_label="Methylparaben",
        category=CATEGORY_CONTACT,
        subcategory="Preservatives",
        common_names=("methylparaben", "methyl 4-hydroxybenzoate"),
        cas_number="99-76-3",
        eu_annex_iii=True,
        regulatory_ref="EU Annex V/12",
    ),
    CompoundEntry(
        key="propylparaben",
        inci_name="Propylparaben",
        display_label="Propylparaben",
        category=CATEGORY_CONTACT,
        subcategory="Preservatives",
        common_names=("propylparaben", "propyl 4-hydroxybenzoate"),
        cas_number="94-13-3",
        eu_annex_iii=True,
        regulatory_ref="EU Annex V/12",
    ),
    CompoundEntry(
        key="butylparaben",
        inci_name="Butylparaben",
        display_label="Butylparaben",
        category=CATEGORY_CONTACT,
        subcategory="Preservatives",
        common_names=("butylparaben", "butyl 4-hydroxybenzoate"),
        cas_number="94-26-8",
        eu_annex_iii=True,
        regulatory_ref="EU Annex V/12",
    ),
    CompoundEntry(
        key="ethylparaben",
        inci_name="Ethylparaben",
        display_label="Ethylparaben",
        category=CATEGORY_CONTACT,
        subcategory="Preservatives",
        common_names=("ethylparaben", "ethyl 4-hydroxybenzoate"),
        cas_number="120-47-8",
        eu_annex_iii=True,
        regulatory_ref="EU Annex V/12",
    ),
    CompoundEntry(
        key="formaldehyde",
        inci_name="Formaldehyde",
        display_label="Formaldehyde",
        category=CATEGORY_CONTACT,
        subcategory="Preservatives",
        common_names=("formaldehyde", "formalin", "methanal"),
        cas_number="50-00-0",
        eu_annex_iii=True,
        regulatory_ref="EU Annex V/5 (max 0.1%)",
    ),
    # Formaldehyde releasers decomposed
    CompoundEntry(
        key="dmdm_hydantoin",
        inci_name="DMDM Hydantoin",
        display_label="DMDM Hydantoin",
        category=CATEGORY_CONTACT,
        subcategory="Preservatives",
        common_names=("DMDM hydantoin",),
        cas_number="6440-58-0",
        eu_annex_iii=True,
        regulatory_ref="EU Annex V/31",
    ),
    CompoundEntry(
        key="imidazolidinyl_urea",
        inci_name="Imidazolidinyl Urea",
        display_label="Imidazolidinyl Urea",
        category=CATEGORY_CONTACT,
        subcategory="Preservatives",
        common_names=("imidazolidinyl urea", "Germall 115"),
        cas_number="39236-46-9",
        eu_annex_iii=True,
        regulatory_ref="EU Annex V/24",
    ),
    CompoundEntry(
        key="diazolidinyl_urea",
        inci_name="Diazolidinyl Urea",
        display_label="Diazolidinyl Urea",
        category=CATEGORY_CONTACT,
        subcategory="Preservatives",
        common_names=("diazolidinyl urea", "Germall II"),
        cas_number="78491-02-8",
        eu_annex_iii=True,
        regulatory_ref="EU Annex V/25",
    ),
    CompoundEntry(
        key="quaternium_15",  # gitleaks:allow
        inci_name="Quaternium-15",
        display_label="Quaternium-15",
        category=CATEGORY_CONTACT,
        subcategory="Preservatives",
        common_names=("quaternium-15", "Dowicil 200"),
        cas_number="51229-78-8",
        eu_annex_iii=True,
        regulatory_ref="EU Annex V/31",
    ),
    CompoundEntry(
        key="methylisothiazolinone",
        inci_name="Methylisothiazolinone",
        display_label="Methylisothiazolinone (MI)",
        category=CATEGORY_CONTACT,
        subcategory="Preservatives",
        common_names=("MI", "methylisothiazolinone"),
        cas_number="2682-20-4",
        eu_annex_iii=True,
        regulatory_ref="EU Annex V/57 (rinse-off only)",
    ),
    CompoundEntry(
        key="methylchloroisothiazolinone",
        inci_name="Methylchloroisothiazolinone",
        display_label="Methylchloroisothiazolinone (MCI)",
        category=CATEGORY_CONTACT,
        subcategory="Preservatives",
        common_names=("MCI", "methylchloroisothiazolinone", "Kathon CG"),
        cas_number="26172-55-4",
        eu_annex_iii=True,
        regulatory_ref="EU Annex V/39 (with MI, rinse-off only)",
    ),
    CompoundEntry(
        key="benzalkonium_chloride",
        inci_name="Benzalkonium Chloride",
        display_label="Benzalkonium Chloride",
        category=CATEGORY_CONTACT,
        subcategory="Preservatives",
        common_names=("benzalkonium chloride", "BAK", "BAC"),
        cas_number="63449-41-2",
        eu_annex_iii=True,
        regulatory_ref="EU Annex V/54",
    ),
    CompoundEntry(
        key="bronopol",
        inci_name="Bronopol",
        display_label="Bronopol",
        category=CATEGORY_CONTACT,
        subcategory="Preservatives",
        common_names=("bronopol", "2-bromo-2-nitropropane-1,3-diol"),
        cas_number="52-51-7",
        eu_annex_iii=True,
        regulatory_ref="EU Annex V/23",
    ),
    CompoundEntry(
        key="iodopropynyl_butylcarbamate",
        inci_name="Iodopropynyl Butylcarbamate",
        display_label="Iodopropynyl Butylcarbamate",
        category=CATEGORY_CONTACT,
        subcategory="Preservatives",
        common_names=("IPBC", "iodopropynyl butylcarbamate"),
        cas_number="55406-53-6",
        eu_annex_iii=True,
        regulatory_ref="EU Annex V/56",
    ),
)

_PROTEINS_AND_EXTRACTS: Final[tuple[CompoundEntry, ...]] = (
    CompoundEntry(
        key="collagen",
        inci_name="Collagen",
        display_label="Collagen",
        category=CATEGORY_CONTACT,
        subcategory="Proteins & Extracts",
        common_names=("collagen", "hydrolyzed collagen"),
        cas_number="9007-34-5",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="keratin",
        inci_name="Keratin",
        display_label="Keratin",
        category=CATEGORY_CONTACT,
        subcategory="Proteins & Extracts",
        common_names=("keratin", "hydrolyzed keratin"),
        cas_number="68238-35-7",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="silk_protein",
        inci_name="Hydrolyzed Silk",
        display_label="Silk Protein",
        category=CATEGORY_CONTACT,
        subcategory="Proteins & Extracts",
        common_names=("silk protein", "hydrolyzed silk", "sericin"),
        cas_number="96690-41-4",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="wheat_protein",
        inci_name="Hydrolyzed Wheat Protein",
        display_label="Wheat Protein",
        category=CATEGORY_CONTACT,
        subcategory="Proteins & Extracts",
        common_names=(
            "wheat protein",
            "hydrolyzed wheat protein",
            "gluten",
            "wheat gluten",
        ),
        cas_number="94350-06-8",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="soy_protein",
        inci_name="Hydrolyzed Soy Protein",
        display_label="Soy Protein",
        category=CATEGORY_CONTACT,
        subcategory="Proteins & Extracts",
        common_names=(
            "soy protein",
            "hydrolyzed soy protein",
            "soybean protein",
            "Glycine Soja Protein",
            "Glycine Max Protein",
        ),
        cas_number="68607-88-5",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="beeswax",
        inci_name="Cera Alba",
        display_label="Beeswax",
        category=CATEGORY_CONTACT,
        subcategory="Proteins & Extracts",
        common_names=("beeswax", "cera alba"),
        cas_number="8012-89-3",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="propolis",
        inci_name="Propolis Extract",
        display_label="Propolis",
        category=CATEGORY_CONTACT,
        subcategory="Proteins & Extracts",
        common_names=("propolis", "bee glue"),
        cas_number="85665-41-4",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="royal_jelly",
        inci_name="Royal Jelly Extract",
        display_label="Royal Jelly",
        category=CATEGORY_CONTACT,
        subcategory="Proteins & Extracts",
        common_names=("royal jelly",),
        cas_number="8031-67-2",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
)

_SUNSCREEN_INGREDIENTS: Final[tuple[CompoundEntry, ...]] = (
    CompoundEntry(
        key="oxybenzone",
        inci_name="Benzophenone-3",
        display_label="Oxybenzone (Benzophenone-3)",
        category=CATEGORY_CONTACT,
        subcategory="Sunscreen Ingredients",
        common_names=("oxybenzone", "benzophenone-3", "BP-3"),
        cas_number="131-57-7",
        eu_annex_iii=False,
        regulatory_ref="EU Annex VI/4",
    ),
    CompoundEntry(
        key="octinoxate",
        inci_name="Ethylhexyl Methoxycinnamate",
        display_label="Octinoxate (Octyl Methoxycinnamate)",
        category=CATEGORY_CONTACT,
        subcategory="Sunscreen Ingredients",
        common_names=("octinoxate", "octyl methoxycinnamate", "OMC"),
        cas_number="5466-77-3",
        eu_annex_iii=False,
        regulatory_ref="EU Annex VI/12",
    ),
    CompoundEntry(
        key="avobenzone",
        inci_name="Butyl Methoxydibenzoylmethane",
        display_label="Avobenzone",
        category=CATEGORY_CONTACT,
        subcategory="Sunscreen Ingredients",
        common_names=("avobenzone", "parsol 1789"),
        cas_number="70356-09-1",
        eu_annex_iii=False,
        regulatory_ref="EU Annex VI/10",
    ),
    CompoundEntry(
        key="octocrylene",
        inci_name="Octocrylene",
        display_label="Octocrylene",
        category=CATEGORY_CONTACT,
        subcategory="Sunscreen Ingredients",
        common_names=("octocrylene",),
        cas_number="6197-30-4",
        eu_annex_iii=False,
        regulatory_ref="EU Annex VI/10",
    ),
    CompoundEntry(
        key="homosalate",
        inci_name="Homosalate",
        display_label="Homosalate",
        category=CATEGORY_CONTACT,
        subcategory="Sunscreen Ingredients",
        common_names=("homosalate",),
        cas_number="118-56-9",
        eu_annex_iii=False,
        regulatory_ref="EU Annex VI/3",
    ),
    CompoundEntry(
        key="titanium_dioxide",
        inci_name="Titanium Dioxide",
        display_label="Titanium Dioxide",
        category=CATEGORY_CONTACT,
        subcategory="Sunscreen Ingredients",
        common_names=("titanium dioxide", "TiO2", "CI 77891"),
        cas_number="13463-67-7",
        eu_annex_iii=False,
        regulatory_ref="EU Annex VI/27",
    ),
    CompoundEntry(
        key="zinc_oxide",
        inci_name="Zinc Oxide",
        display_label="Zinc Oxide",
        category=CATEGORY_CONTACT,
        subcategory="Sunscreen Ingredients",
        common_names=("zinc oxide", "ZnO"),
        cas_number="1314-13-2",
        eu_annex_iii=False,
        regulatory_ref="EU Annex VI/30",
    ),
)

# --- Surfactants (expanded abbreviation keys) ---
_SURFACTANTS_AND_EMULSIFIERS: Final[tuple[CompoundEntry, ...]] = (
    CompoundEntry(
        key="sodium_lauryl_sulfate",
        inci_name="Sodium Lauryl Sulfate",
        display_label="Sodium Lauryl Sulfate (SLS)",
        category=CATEGORY_CONTACT,
        subcategory="Surfactants & Emulsifiers",
        common_names=("SLS", "sodium lauryl sulfate", "sodium dodecyl sulfate"),
        cas_number="151-21-3",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="sodium_laureth_sulfate",
        inci_name="Sodium Laureth Sulfate",
        display_label="Sodium Laureth Sulfate (SLES)",
        category=CATEGORY_CONTACT,
        subcategory="Surfactants & Emulsifiers",
        common_names=("SLES", "sodium laureth sulfate"),
        cas_number="9004-82-4",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="cocamidopropyl_betaine",
        inci_name="Cocamidopropyl Betaine",
        display_label="Cocamidopropyl Betaine",
        category=CATEGORY_CONTACT,
        subcategory="Surfactants & Emulsifiers",
        common_names=("cocamidopropyl betaine", "CAPB"),
        cas_number="61789-40-0",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    # PEG compounds decomposed
    CompoundEntry(
        key="peg_4",
        inci_name="PEG-4",
        display_label="PEG-4",
        category=CATEGORY_CONTACT,
        subcategory="Surfactants & Emulsifiers",
        common_names=("PEG-4", "polyethylene glycol 200"),
        cas_number="25322-68-3",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="peg_40_hydrogenated_castor_oil",  # gitleaks:allow
        inci_name="PEG-40 Hydrogenated Castor Oil",
        display_label="PEG-40 Hydrogenated Castor Oil",
        category=CATEGORY_CONTACT,
        subcategory="Surfactants & Emulsifiers",
        common_names=("PEG-40 hydrogenated castor oil", "Cremophor RH 40"),
        cas_number="61788-85-0",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="peg_100_stearate",
        inci_name="PEG-100 Stearate",
        display_label="PEG-100 Stearate",
        category=CATEGORY_CONTACT,
        subcategory="Surfactants & Emulsifiers",
        common_names=("PEG-100 stearate",),
        cas_number="9004-99-3",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    # Polysorbates decomposed
    CompoundEntry(
        key="polysorbate_20",  # gitleaks:allow
        inci_name="Polysorbate 20",
        display_label="Polysorbate 20",
        category=CATEGORY_CONTACT,
        subcategory="Surfactants & Emulsifiers",
        common_names=("polysorbate 20", "Tween 20"),
        cas_number="9005-64-5",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="polysorbate_60",  # gitleaks:allow
        inci_name="Polysorbate 60",
        display_label="Polysorbate 60",
        category=CATEGORY_CONTACT,
        subcategory="Surfactants & Emulsifiers",
        common_names=("polysorbate 60", "Tween 60"),
        cas_number="9005-67-8",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="polysorbate_80",  # gitleaks:allow
        inci_name="Polysorbate 80",
        display_label="Polysorbate 80",
        category=CATEGORY_CONTACT,
        subcategory="Surfactants & Emulsifiers",
        common_names=("polysorbate 80", "Tween 80"),
        cas_number="9005-65-6",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="sodium_lauroyl_sarcosinate",
        inci_name="Sodium Lauroyl Sarcosinate",
        display_label="Sodium Lauroyl Sarcosinate",
        category=CATEGORY_CONTACT,
        subcategory="Surfactants & Emulsifiers",
        common_names=("sodium lauroyl sarcosinate",),
        cas_number="137-16-6",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
)

_OTHER_GENERAL_CONTACT: Final[tuple[CompoundEntry, ...]] = (
    CompoundEntry(
        key="retinol",
        inci_name="Retinol",
        display_label="Retinol/Retinoids",
        category=CATEGORY_CONTACT,
        subcategory="Other General Contact",
        common_names=("retinol", "vitamin A", "retinoids", "retinyl palmitate"),
        cas_number="68-26-8",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="vitamin_c",
        inci_name="Ascorbic Acid",
        display_label="Vitamin C (L-Ascorbic Acid)",
        category=CATEGORY_CONTACT,
        subcategory="Other General Contact",
        common_names=("vitamin C", "L-ascorbic acid", "ascorbic acid"),
        cas_number="50-81-7",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="niacinamide",
        inci_name="Niacinamide",
        display_label="Niacinamide",
        category=CATEGORY_CONTACT,
        subcategory="Other General Contact",
        common_names=("niacinamide", "nicotinamide", "vitamin B3"),
        cas_number="98-92-0",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="propylene_glycol",
        inci_name="Propylene Glycol",
        display_label="Propylene Glycol",
        category=CATEGORY_CONTACT,
        subcategory="Other General Contact",
        common_names=("propylene glycol", "1,2-propanediol"),
        cas_number="57-55-6",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="butylene_glycol",
        inci_name="Butylene Glycol",
        display_label="Butylene Glycol",
        category=CATEGORY_CONTACT,
        subcategory="Other General Contact",
        common_names=("butylene glycol", "1,3-butanediol"),
        cas_number="107-88-0",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="dimethicone",
        inci_name="Dimethicone",
        display_label="Dimethicone",
        category=CATEGORY_CONTACT,
        subcategory="Other General Contact",
        common_names=("dimethicone", "polydimethylsiloxane", "PDMS"),
        cas_number="9006-65-9",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="tocopherol",
        inci_name="Tocopherol",
        display_label="Tocopherol (Vitamin E)",
        category=CATEGORY_CONTACT,
        subcategory="Other General Contact",
        common_names=("tocopherol", "vitamin E", "alpha-tocopherol"),
        cas_number="59-02-9",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="alcohol_denat",
        inci_name="Alcohol Denat.",
        display_label="Alcohol Denat",
        category=CATEGORY_CONTACT,
        subcategory="Other General Contact",
        common_names=("alcohol denat", "denatured alcohol", "SD alcohol"),
        cas_number="64-17-5",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="isopropyl_alcohol",
        inci_name="Isopropyl Alcohol",
        display_label="Isopropyl Alcohol",
        category=CATEGORY_CONTACT,
        subcategory="Other General Contact",
        common_names=("isopropyl alcohol", "isopropanol", "rubbing alcohol"),
        cas_number="67-63-0",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
)

# --- Food-Derived Skincare Ingredients (new subcategory) ---
_FOOD_DERIVED_INGREDIENTS: Final[tuple[CompoundEntry, ...]] = (
    CompoundEntry(
        key="albumin",
        inci_name="Albumin",
        display_label="Albumin",
        category=CATEGORY_CONTACT,
        subcategory="Food-Derived Ingredients",
        common_names=("albumin", "egg albumin", "ovalbumin"),
        cas_number="9006-59-1",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="almond_oil",
        inci_name="Prunus Amygdalus Dulcis Oil",
        display_label="Almond Oil",
        category=CATEGORY_CONTACT,
        subcategory="Food-Derived Ingredients",
        common_names=("almond oil", "sweet almond oil", "prunus amygdalus dulcis oil"),
        cas_number="8007-69-0",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="coconut_oil",
        inci_name="Cocos Nucifera Oil",
        display_label="Coconut Oil",
        category=CATEGORY_CONTACT,
        subcategory="Food-Derived Ingredients",
        common_names=("coconut oil", "cocos nucifera oil"),
        cas_number="8001-31-8",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="oat_extract",
        inci_name="Avena Sativa Kernel Extract",
        display_label="Oat Extract",
        category=CATEGORY_CONTACT,
        subcategory="Food-Derived Ingredients",
        common_names=("oat extract", "colloidal oatmeal", "avena sativa"),
        cas_number="84012-26-0",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="soy_extract",
        inci_name="Glycine Soja Extract",
        display_label="Soy Extract",
        category=CATEGORY_CONTACT,
        subcategory="Food-Derived Ingredients",
        common_names=(
            "soy extract",
            "soybean extract",
            "glycine soja",
            "Glycine Soja Seed Extract",
            "Glycine Soja Germ Extract",
        ),
        cas_number="84776-91-0",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="shea_butter",
        inci_name="Butyrospermum Parkii Butter",
        display_label="Shea Butter",
        category=CATEGORY_CONTACT,
        subcategory="Food-Derived Ingredients",
        common_names=("shea butter", "butyrospermum parkii butter"),
        cas_number="194043-92-0",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="jojoba_oil",
        inci_name="Simmondsia Chinensis Seed Oil",
        display_label="Jojoba Oil",
        category=CATEGORY_CONTACT,
        subcategory="Food-Derived Ingredients",
        common_names=("jojoba oil", "simmondsia chinensis seed oil"),
        cas_number="61789-91-1",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="argan_oil",
        inci_name="Argania Spinosa Kernel Oil",
        display_label="Argan Oil",
        category=CATEGORY_CONTACT,
        subcategory="Food-Derived Ingredients",
        common_names=("argan oil",),
        cas_number="223747-87-1",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="macadamia_oil",
        inci_name="Macadamia Integrifolia Seed Oil",
        display_label="Macadamia Oil",
        category=CATEGORY_CONTACT,
        subcategory="Food-Derived Ingredients",
        common_names=("macadamia oil", "macadamia nut oil"),
        cas_number="129811-19-4",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
    CompoundEntry(
        key="avocado_oil",
        inci_name="Persea Gratissima Oil",
        display_label="Avocado Oil",
        category=CATEGORY_CONTACT,
        subcategory="Food-Derived Ingredients",
        common_names=("avocado oil", "persea gratissima oil"),
        cas_number="8024-32-6",
        eu_annex_iii=False,
        regulatory_ref="",
    ),
)


# ============================================================================
# Assembled catalog
# ============================================================================

COMPOUNDS: Final[tuple[CompoundEntry, ...]] = (
    *_ACIDS_AND_EXFOLIANTS,
    *_BOTANICALS_AND_ESSENTIAL_OILS,
    *_COLORANTS_AND_DYES,
    *_GENERAL_CONTACT_ALLERGENS,
    *_FRAGRANCES,
    *_PRESERVATIVES,
    *_PROTEINS_AND_EXTRACTS,
    *_SUNSCREEN_INGREDIENTS,
    *_SURFACTANTS_AND_EMULSIFIERS,
    *_OTHER_GENERAL_CONTACT,
    *_FOOD_DERIVED_INGREDIENTS,
)


# ============================================================================
# Derived lookup — FLAT_ALLERGEN_LABEL_MAP
# ============================================================================


def _build_flat_allergen_label_map(
    compounds: tuple[CompoundEntry, ...],
) -> dict[str, str]:
    """Build a flat dict mapping allergen_key → display_label."""
    return {c.key: c.display_label for c in compounds}


FLAT_ALLERGEN_LABEL_MAP: Final[dict[str, str]] = _build_flat_allergen_label_map(
    COMPOUNDS
)


# ============================================================================
# Import-time validation
# ============================================================================


def _assert_entries_well_formed(compounds: tuple[CompoundEntry, ...]) -> None:
    """Validate that every CompoundEntry has required non-empty fields."""
    for i, entry in enumerate(compounds):
        if not isinstance(entry, CompoundEntry):
            raise AssertionError(
                f"Entry at index {i} is not a CompoundEntry: {entry!r}"
            )
        if not entry.key:
            raise AssertionError(f"Entry at index {i} has empty key: {entry!r}")
        if not entry.display_label:
            raise AssertionError(
                f"Entry at index {i} has empty display_label: {entry!r}"
            )
        if not entry.category:
            raise AssertionError(f"Entry at index {i} has empty category: {entry!r}")
        if not entry.subcategory:
            raise AssertionError(f"Entry at index {i} has empty subcategory: {entry!r}")
        # Validate key format: lowercase, underscored, no special chars
        if entry.key != entry.key.lower():
            raise AssertionError(f"Key {entry.key!r} at index {i} is not lowercase")
        if " " in entry.key or "-" in entry.key or "'" in entry.key:
            raise AssertionError(
                f"Key {entry.key!r} at index {i} contains spaces, hyphens, "
                "or apostrophes"
            )


def _assert_keys_unique(compounds: tuple[CompoundEntry, ...]) -> None:
    """Validate that all allergen keys are unique across the entire catalog."""
    seen: dict[str, str] = {}  # key -> subcategory
    duplicates: list[str] = []

    for entry in compounds:
        if entry.key in seen:
            duplicates.append(
                f"  {entry.key!r}: first in {seen[entry.key]!r},"
                f" also in {entry.subcategory!r}"
            )
        else:
            seen[entry.key] = entry.subcategory

    if duplicates:
        raise AssertionError(
            "Duplicate allergen keys detected:\n" + "\n".join(duplicates)
        )


_assert_entries_well_formed(COMPOUNDS)
_assert_keys_unique(COMPOUNDS)
