# Generated by Django 6.0.2 on 2026-03-16 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('food', 'Food Allergens'), ('contact', 'Contact/Topical Allergens'), ('inhalant', 'Inhalant Allergens'), ('other', 'Other Allergens')], db_index=True, default='other', help_text='Generic allergen category', max_length=15)),
                ('allergen_key', models.CharField(choices=[], db_index=True, help_text='Specific allergen (choices filtered via category)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text="Inactive allergens won't be shown in user selection")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Allergen',
                'verbose_name_plural': 'Allergens',
                'ordering': ['category', 'allergen_key'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='allergen_cat_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('category', 'allergen_key'), name='uniq_category_allergen')],
            },
        ),
        migrations.CreateModel(
            name='UserAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity_level', models.CharField(blank=True, choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('life_threatening', 'Life-Threatening')], default='', help_text='Optional severity level of the allergy', max_length=20)),
                ('is_confirmed', models.BooleanField(default=False, help_text='Clinically confirmed: True/False')),
                ('symptom_onset_date', models.DateField(blank=True, help_text='Date when symptoms first appeared', null=True)),
                ('source_info', models.CharField(blank=True, choices=[('self_reported', 'Self-Reported'), ('medical_professional', 'Medical Professional'), ('allergy_test', 'Formal Allergy Test'), ('family_history', 'Family History')], default='', help_text='Source of allergy information', max_length=20)),
                ('user_reaction_details', models.JSONField(blank=True, default=dict, help_text='Past reactions: {symptom: str, severity: str, date: str}')),
                ('admin_notes', models.JSONField(blank=True, default=dict, help_text='Internal notes: {verified_by: str, verification_date: str}')),
                ('is_active', models.BooleanField(default=True, help_text="Inactive user allergies won't be considered in assessments")),
                ('allergen', models.ForeignKey(help_text='The allergen this user is allergic to', on_delete=django.db.models.deletion.CASCADE, related_name='user_allergy_entries', to='allergies.allergen')),
                ('user', models.ForeignKey(help_text='The user who has this allergy', on_delete=django.db.models.deletion.CASCADE, related_name='user_allergies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Allergy',
                'verbose_name_plural': 'User Allergies',
                'ordering': ['user', 'allergen__category', 'allergen__allergen_key'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='user_allergy_user_idx'), models.Index(fields=['allergen', 'is_active'], name='user_allergy_alrgn_idx'), models.Index(fields=['is_confirmed', 'is_active'], name='user_allergy_conf_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'allergen'), name='uniq_user_allergen')],
            },
        ),
    ]
