# Generated by Django 6.0 on 2026-02-19 19:10

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allergies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userallergy',
            name='user',
            field=models.ForeignKey(help_text='The user who has this allergy', on_delete=django.db.models.deletion.CASCADE, related_name='allergic_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userallergy',
            index=models.Index(fields=['user', 'is_active'], name='user_allergy_user_idx'),
        ),
        migrations.AddIndex(
            model_name='userallergy',
            index=models.Index(fields=['allergen', 'is_active'], name='user_allergy_alrgn_idx'),
        ),
        migrations.AddIndex(
            model_name='userallergy',
            index=models.Index(fields=['is_confirmed', 'is_active'], name='user_allergy_conf_idx'),
        ),
        migrations.AddConstraint(
            model_name='userallergy',
            constraint=models.UniqueConstraint(fields=('user', 'allergen'), name='uniq_user_allergen'),
        ),
        migrations.AddConstraint(
            model_name='userallergy',
            constraint=models.CheckConstraint(condition=models.Q(('symptom_onset_date__lte', django.db.models.functions.datetime.Now())), name='symptom_onset_not_future'),
        ),
    ]
