# Generated by Django 6.0 on 2026-02-28 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allergies', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userallergy',
            name='symptom_onset_not_future',
        ),
    ]
