# Generated by Django 6.0.2 on 2026-03-16 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergies', '0003_remove_symptom_onset_check_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userallergy',
            name='user',
            field=models.ForeignKey(help_text='The user who has this allergy', on_delete=django.db.models.deletion.CASCADE, related_name='user_allergies', to=settings.AUTH_USER_MODEL),
        ),
    ]
