# Generated by Django 6.0.2 on 2026-03-16 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergies', '0004_rename_related_name_user_allergies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userallergy',
            name='allergen',
            field=models.ForeignKey(help_text='The allergen this user is allergic to', on_delete=django.db.models.deletion.CASCADE, related_name='user_allergy_entries', to='allergies.allergen'),
        ),
    ]
